/* Maps rf_outputs_t to Matter attributes (docs/matter.md).
 * Base: the "Matter - SoC Occupancy Sensor" example of the Silicon Labs Matter
 * extension, with the endpoints from docs/matter.md added in ZAP.
 * NOT built on the development PC (no SDK). */
#include <app-common/zap-generated/attributes/Accessors.h>
#include <app/clusters/occupancy-sensor-server/occupancy-sensor-server.h>
#include <platform/CHIPDeviceLayer.h>

#include <atomic>
#include <cstring>

extern "C" {
#include "app.h"
#include "features_v1.h"
#include "nn.h"
}

using namespace chip;
using namespace chip::app::Clusters;

namespace {
constexpr EndpointId kEpRoom = 1;
constexpr EndpointId kEpZone0 = 2;    // 2..4
constexpr EndpointId kEpFall = 5;
constexpr EndpointId kEpUncertain = 6;

rf_outputs_t sPending;    // written by the radar task before ScheduleWork
rf_outputs_t sPublished;  // Matter thread only
rf_outputs_t sLastSent;   // radar task only
std::atomic<bool> sScheduled{false};
uint32_t sLastReportMs = 0;

void SetOccupancy(EndpointId ep, bool on)
{
    OccupancySensing::Attributes::Occupancy::Set(ep, on ? OccupancySensing::OccupancyBitmap::kOccupied
                                                        : static_cast<OccupancySensing::OccupancyBitmap>(0));
}

void Publish(intptr_t)
{
    sScheduled = false;
    static bool sStaticDone = false;
    if (!sStaticDone) {
        // Firmware identity: feature contract version and embedded model.
        StillpointPresence::Attributes::ContractVersion::Set(kEpRoom, RF_CONTRACT_VERSION);
        StillpointPresence::Attributes::ModelHash::Set(kEpRoom, rf_nn_model_hash());
        sStaticDone = true;
    }
    const rf_outputs_t o = sPending;   // copy taken on the Matter thread
    if (o.occupied != sPublished.occupied) {
        SetOccupancy(kEpRoom, o.occupied);
    }
    for (int z = 0; z < RF_APP_MAX_ZONES; z++) {
        if (o.zone_occupied[z] != sPublished.zone_occupied[z]) {
            SetOccupancy(static_cast<EndpointId>(kEpZone0 + z), o.zone_occupied[z]);
        }
    }
    // Fall confirmed OR uncertain: a possible fall that cannot be verified is reported.
    if (o.fall_alarm != sPublished.fall_alarm) {
        BooleanState::Attributes::StateValue::Set(kEpFall, o.fall_alarm);
    }
    if (o.uncertain != sPublished.uncertain) {
        BooleanState::Attributes::StateValue::Set(kEpUncertain, o.uncertain);
    }
    // Manufacturer cluster (stillpoint_cluster.xml) on EP1: count and detailed fall
    // state. Accessors generated by ZAP for cluster 0xFFF1FC01.
    if (o.count != sPublished.count) {
        StillpointPresence::Attributes::PersonCount::Set(kEpRoom, o.count);
    }
    if (o.worst_fall != sPublished.worst_fall) {
        StillpointPresence::Attributes::FallState::Set(kEpRoom, static_cast<uint8_t>(o.worst_fall));
    }
    if (o.uncertain != sPublished.uncertain) {
        StillpointPresence::Attributes::Uncertain::Set(kEpRoom, o.uncertain);
    }
    if (o.n_proposed_exclusions != sPublished.n_proposed_exclusions) {
        StillpointPresence::Attributes::ProposedExclusions::Set(kEpRoom, o.n_proposed_exclusions);
    }
    sPublished = o;
}
} // namespace

extern "C" void rf_matter_publish(const rf_outputs_t * out)
{
    // Called from the radar task at 10 Hz. Work is scheduled on the Matter thread
    // only when something publishable changed, at most twice per second, except
    // for a fall alarm, which goes out immediately.
    const uint32_t now = static_cast<uint32_t>(chip::System::SystemClock().GetMonotonicMilliseconds64().count());
    // Compared with the last state sent from this task, without reading Matter
    // thread state. A change held back by the rate limit is retried on the next frame.
    const bool changed = out->occupied != sLastSent.occupied || out->fall_alarm != sLastSent.fall_alarm ||
        out->uncertain != sLastSent.uncertain || out->count != sLastSent.count ||
        out->worst_fall != sLastSent.worst_fall || out->n_proposed_exclusions != sLastSent.n_proposed_exclusions ||
        std::memcmp(out->zone_occupied, sLastSent.zone_occupied, sizeof(out->zone_occupied)) != 0;
    const bool urgent = out->fall_alarm && !sLastSent.fall_alarm;
    if (!changed || (!urgent && now - sLastReportMs < 500) || sScheduled.exchange(true)) {
        return;
    }
    sLastReportMs = now;
    sPending = *out;
    sLastSent = *out;
    DeviceLayer::PlatformMgr().ScheduleWork(Publish, 0);
}
