M48
; DRILL file KiCad 10.0.6-10.0.6~ubuntu24.04.1 date 2026-10-06T01:35:56
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-06T01:35:56+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6-10.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.580
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.660
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.991
%
G90
G05
T2
X96.25Y-116.0
T3
X77.46Y-113.0
X82.54Y-111.984
X82.54Y-114.016
T1
X103.54Y-116.0G85X103.96Y-116.0
G05
M30
