"""Simple 3D models (dimensioned boxes) of the custom parts in hardware/lib/radar60.pretty.

Writes a coloured .wrl per part (KiCad 3D viewer) and, when run with the
FreeCAD interpreter, the .step as well (the board STEP export: kicad-cli
swaps the .wrl for the .step of the same name).

  python tools/gen_3d_models.py                       -> .wrl only
  "C:\\Program Files\\FreeCAD 1.1\\bin\\freecadcmd.exe" -c "exec(open(r'tools/gen_3d_models.py').read())"   -> .wrl + .step

Millimetres, footprint frame with Y up (KiCad flips Y when it places
the model): a footprint point (x, y) is (x, -y) here.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__)) if "__file__" in globals() else os.path.join(os.getcwd(), "tools")
OUT = os.path.join(HERE, "..", "hardware", "lib", "radar60.3dshapes")
os.makedirs(OUT, exist_ok=True)

BLACK = (0.08, 0.08, 0.09)
FR4 = (0.13, 0.33, 0.20)
METAL = (0.78, 0.78, 0.80)
GOLD = (0.85, 0.68, 0.25)
WHITE = (0.93, 0.93, 0.90)
LENS = (0.85, 0.88, 0.95)

# (name, [(x0, y0, z0, x1, y1, z1, colour)])
MODELS = {
    # BGT60TR13C, PG-VF2BGA-40-1: 6.5 x 5.0 x 0.9 mm, body offset (-0.17, -0.17) in the footprint.
    # Antennas on the top face: 1 TX + 3 RX (gold patches, approximate positions).
    "Infineon_PG-VF2BGA-40-1": [
        (-3.42, -2.33, 0.0, 3.08, 2.67, 0.9, BLACK),
        (-2.6, 0.9, 0.9, -1.4, 2.1, 0.92, GOLD),      # TX
        (0.4, 0.9, 0.9, 1.4, 1.9, 0.92, GOLD),        # RX1
        (1.65, 0.9, 0.9, 2.65, 1.9, 0.92, GOLD),      # RX2
        (0.4, -1.6, 0.9, 1.4, -0.6, 0.92, GOLD),      # RX3
    ],
    # MGM260P: 12.9 x 15.0 mm, A = 2.15 mm (PCB 0.8 + shield 1.35), shield 11.8 x 8.4 at 0.49 mm from the edge
    # opposite the antenna (datasheet fig. 8.1). Antenna on the pad 1/36 side (Y+ here).
    "SiliconLabs_MGM260P": [
        (-6.45, -7.5, 0.0, 6.45, 7.5, 0.8, FR4),
        (-5.9, -7.01, 0.8, 5.9, 1.39, 2.15, METAL),
        (-4.2, 5.6, 0.8, 4.2, 6.0, 0.83, GOLD),       # printed antenna (indicative)
        (-4.2, 3.4, 0.8, -3.8, 6.0, 0.83, GOLD),
    ],
    # G-Switch GT-USB-7051A vertical: shell 8.94 x 3.16 x 7.5 mm above the board (drawing 2019-05-29);
    # 8.34 x 2.56 mouth with a centre tongue.
    "USB_C_GT-USB-7051A": [
        (-4.47, -1.58, 0.0, -4.17, 1.58, 7.5, METAL),
        (4.17, -1.58, 0.0, 4.47, 1.58, 7.5, METAL),
        (-4.17, -1.58, 0.0, 4.17, -1.28, 7.5, METAL),
        (-4.17, 1.28, 0.0, 4.17, 1.58, 7.5, METAL),
        (-4.17, -1.28, 0.0, 4.17, 1.28, 0.8, BLACK),
        (-3.3, -0.35, 0.8, 3.3, 0.35, 6.9, BLACK),
        (-5.2, -2.6, 0.0, -4.47, -1.9, 0.3, METAL),
        (4.47, -2.6, 0.0, 5.2, -1.9, 0.3, METAL),
        (-5.2, 1.9, 0.0, -4.47, 2.6, 0.3, METAL),
        (4.47, 1.9, 0.0, 5.2, 2.6, 0.3, METAL),
    ],
    # Yongyu SZYY1615RGB-B: 1.5 x 1.6 x 0.55 mm (LCSC pattern); lens on a white base.
    "LED_RGB_1615_SZYY1615RGB-B": [
        (-0.75, -0.8, 0.0, 0.75, 0.8, 0.3, WHITE),
        (-0.6, -0.65, 0.3, 0.6, 0.65, 0.55, LENS),
    ],
}


def box_faces(x0, y0, z0, x1, y1, z1):
    v = [(x0, y0, z0), (x1, y0, z0), (x1, y1, z0), (x0, y1, z0),
         (x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1)]
    f = [(0, 3, 2, 1), (4, 5, 6, 7), (0, 1, 5, 4), (1, 2, 6, 5), (2, 3, 7, 6), (3, 0, 4, 7)]
    return v, f


def write_wrl(name, boxes):
    s = 1 / 2.54   # KiCad VRML units: 0.1 inch
    out = ["#VRML V2.0 utf8", f"# {name} - generated by tools/gen_3d_models.py"]
    for x0, y0, z0, x1, y1, z1, c in boxes:
        v, f = box_faces(x0, y0, z0, x1, y1, z1)
        pts = ", ".join(f"{a * s:.5f} {b * s:.5f} {d * s:.5f}" for a, b, d in v)
        idx = ", ".join(" ".join(str(i) for i in q) + " -1" for q in f)
        out.append("Shape { appearance Appearance { material Material { diffuseColor %.3f %.3f %.3f "
                   "specularColor 0.2 0.2 0.2 shininess 0.3 } }" % c)
        out.append("  geometry IndexedFaceSet { solid TRUE coord Coordinate { point [ %s ] } coordIndex [ %s ] } }" % (pts, idx))
    open(os.path.join(OUT, name + ".wrl"), "w").write("\n".join(out) + "\n")


for name, boxes in MODELS.items():
    write_wrl(name, boxes)

try:
    import FreeCAD as App   # freecadcmd only
    import Part
    for name, boxes in MODELS.items():
        shapes = [Part.makeBox(x1 - x0, y1 - y0, z1 - z0, App.Vector(x0, y0, z0)) for x0, y0, z0, x1, y1, z1, _ in boxes]
        comp = shapes[0].fuse(shapes[1:]) if len(shapes) > 1 else shapes[0]
        comp.exportStep(os.path.join(OUT, name + ".step"))
    print("wrl + step in", os.path.abspath(OUT))
except ImportError:
    print("wrl in", os.path.abspath(OUT), "(STEP: run with freecadcmd)")
